name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout zola
        uses: actions/checkout@v3
        with:
          repository: getzola/zola
          fetch-depth: 0
          submodules: true
      - name: Find latest release
        id: version
        run: echo version=$(git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" "refs/tags/v*") >> ${GITHUB_OUTPUT}
      - name: Switch to version commit
        run: git checkout ${{ steps.version.outputs.version }}
      - name: Install rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y | sh
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build zola
        run: cross build --release --target=aarch64-unknown-linux-gnu --verbose
      - name: Tar files
        run: tar -cvzf zola-aarch64-linux.tar.gz target/aarch64-unknown-linux-gnu/release/zola
      - name: Create package
        uses: actions/upload-artifact@v3
        with:
          path: zola-aarch64-linux.tar.gz
