name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  version: v0.17.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout zola
        uses: actions/checkout@v3
        with:
          repository: getzola/zola
          ref: v0.17.2
          submodules: true
      - name: Install rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y | sh
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build zola
        run: cross build --release --target=aarch64-unknown-linux-gnu --verbose
      - name: Create package
        uses: actions/upload-artifact@v3
        with:
          name: zola-aarch64-linux
          path: target/aarch64-unknown-linux-gnu/release/zola
